spring.application.name=Lab4_Java5
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.root=INFO
logging.level.com.poly.controllers=DEBUG 
logging.file.name=application.log 
spring.messages.encoding=UTF-8
